- name: Create internal Docker network
  docker_network:
    name: internal-network
    driver: bridge
    state: present

- name: Create public Docker network
  docker_network:
    name: public-network
    driver: bridge
    state: present
