- name: Run HTTPD container
  docker_container:
    name: http-server-container
    image: flowmillot/tp-devops-httpd:latest
    state: started
    restart_policy: no
    env:
      BACKEND_HOST: backend-container
    ports:
      - "80:80"
    networks:
      - name: public-network
