- name: Run backend container
  docker_container:
    name: backend-container
    image: flowmillot/tp-devops-simple-api:latest
    state: started
    #If the container does not exist, it will be created and started.
    #If it exists but is stopped, it will be started.
    #If it is already running, no action is taken.
    restart_policy: on-failure
    restart_retries: 3
    networks:
      - name: internal-network
      - name: public-network

