- name: Run backend container
  docker_container:
    name: backend-container
    image: flowmillot/tp-devops-simple-api:latest
    state: started
    restart_policy: on-failure
    restart_retries: 3
    #depends_on:
    #  - postgres-container
    networks:
      - name: internal-network
      - name: public-network
    env:
      DATABASE_URL: "jdbc:postgresql://postgres-container:5432/db"
      DATABASE_USERNAME: "usr"
      DATABASE_PASSWORD: "pwd"
  vars:
    ansible_python_interpreter: /usr/bin/python3
