#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/lauch_front

- name: Run Front container
  docker_container:
    name: front-container
    image: flowmillot/tp-devops-front:latest
    state: started
    restart_policy: no
    networks:
      - name: front-network