- name: Run Postgres container
  docker_container:
    name: postgres-container
    image: flowmillot/tp-devops-postgres:latest
    pull: yes
    state: started
    restart_policy: unless-stopped
    env:
      DB_NAME: db
      USERNAME: usr
      PASSWORD: pwd
      DB_HOST: my-postgres-compose
    networks:
      - name: internal-network
