- name: Run Postgres container
  docker_container:
    name: postgres-container
    image: flowmillot/tp-devops-postgres:latest
    pull: yes
    state: started
    restart_policy: unless-stopped
    networks:
      - name: internal-network
