- name: Run Postgres container
  docker_container:
    name: postgres-container
    image: flowmillot/tp-devops-postgres:latest
    pull: yes
    state: started
    restart_policy: unless-stopped
    env:
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: db
    networks:
      - name: internal-network
