name: Deploy

#This workflow depploys after the "Docker Build and Push" workflow is completed
#Only the main branch is considered
# on:
#   workflow_run:
#     workflows: ["Docker Build and Push"]
#     branches:
#       - main
#     types:
#       - completed

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to server
        run: ansible-playbook -i ./ansible/inventories/setup.yml ./ansible/playbook.yml --become

