name: CI devops

on:
  push:
    branches:
      - main
      - dev

jobs:
  test-backend:
    runs-on: ubuntu-24.04

    steps:
      #Checkout your repository code
      - uses: actions/checkout@v4

      #Set up JDK 21 environment
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      #Build and test your application with Maven
      - name: Build and test with Maven
        working-directory: simpleapi
        run: mvn clean verify